baseURL = 'https://example.org/'
title = "Blog do Marco(Marco's Blog)"
theme = 'risotto'
author = "Marco Pegoraro"
copyright = "© [Marco Pegoraro](https://marcoagpegoraro.com.br)."
paginate = 3
languageCode = "en"
DefaultContentLanguage = "en"

[params.theme]
palette = "base16-dark"

[taxonomies]
category = "categories"
tag = "tags"
series = "series"
post = "posts"

[params.about]
title = "Marco Pegoraro"
description = "Hello, my name is Marco, welcome to my personal blog, here i write posts about tecnology, programming, life, tech reviews among other things."
logo = "💻"
#logo_image = "images/rice.svg"

[[params.socialLinks]]
icon = "fa-brands fa-github"
title = "GitHub"
url = "https://github.com/marcoagpegoraro"

[[params.socialLinks]]
icon = "fa-solid fa-envelope"
title = "Email"
url = "mailto:marco@marcoagpegoraro.com.br"

[[params.socialLinks]]
icon = "fa-brands fa-youtube"
title = "Youtube"
url = "https://www.youtube.com/@marcoagpegoraro"

[[params.socialLinks]]
icon = "fa-brands fa-linkedin"
title = "Linkedin"
url = "https://www.linkedin.com/in/marco-antonio-goncalves"

[[params.socialLinks]]
icon = "fa-brands fa-medium"
title = "Medium"
url = "https://medium.com/@tete5423"

# For hugo >= 0.60.0, enable inline HTML
[markup.goldmark.renderer]
unsafe = true

[markup]

  # Table of contents
  # Add toc = true to content front matter to enable
  [markup.tableOfContents]
    startLevel = 2
    endLevel   = 3
    ordered    = true


[privacy]

  [privacy.vimeo]
    disabled = false
    simple = true

  [privacy.twitter]
    disabled = false
    enableDNT = true
    simple = true

  [privacy.instagram]
    disabled = false
    simple = true

  [privacy.youtube]
    disabled = false
    privacyEnhanced = true

[services]

  [services.instagram]
    disableInlineCSS = true

  [services.twitter]
    disableInlineCSS = true