baseURL = 'https://example.org/'
languageCode = 'en-us'
title = "Blog do Marco(Marco's Blog)"
theme = 'risotto'

# Automatically add content sections to main menu
# sectionPagesMenu = "main"

[taxonomies]
category = "categories"
tag = "tags"
series = "series"
post = "posts"